version: "3"
services:
  redis-db:
    image: redis:latest
    command: redis-server --requirepass redispass
    ports:
      - 6379:6379
  pg-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go_db_crud
    volumes:
      - ./data:/var/lib/postgresql/data
    command: -p 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
  app:
    build: .
    depends_on:
      pg-db:
        condition: service_healthy
    ports:
      - 8080:8080